void main() {
  String linguagem = "Dart";
  /*Switch case, funciona assim , caso  a variavel for igual a opção oferecida 
  pelo lingugame então ele mostra o caso qe for igual a linguagem utilizada
  */

  switch (linguagem) {
    //variavel com o valor
    case "Dart": //caso for Dart , ele printa a linguagem
      print(linguagem);
      break;
    case "Python": //caso a variavel armazenar o valor Python printa a linguagem
      print(linguagem);
      break;
  }
}
